language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update -qq && sudo apt-get install -y gcc-4.7 g++-4.7 gobjc-4.7 llvm-dev; fi
  - if [ $CXX == g++ ]; then export CC=gcc-4.7 && export CXX=g++-4.7; fi

script:
  - cd cctools && ./autogen.sh && ./configure && make
